#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# Show progress, dump number of items that have passed through the stream


from eslib.procs import ShowProgress
import argparse
from eslib.prog import progname, initlogs

def main():
    help_f = "How often should progress get printed. Default: 1000 (i.e. per 1000 items.)"
    parser = argparse.ArgumentParser(usage="\n %(prog)s [-f frequency]")
    parser._actions[0].help = argparse.SUPPRESS
    parser.add_argument("-f", "--frequency", type=int, default=1000, help=help_f)
    parser.add_argument(      "--terminal" , action="store_true")
    parser.add_argument(      "--name"     , help="Process name.", default=None)

    args = parser.parse_args()

    # Set up and run this processor
    dp = ShowProgress(args.name or progname())
    dp.frequency = args.frequency
    dp.terminal = args.terminal

    dp.run()


if __name__ == "__main__": main()
